import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";

import { routes } from "../routes";
import Upload from "../components/shared/Upload";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Uploadly</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Uploadly</h1>

        <p className={styles.description}>
          Get started by uploading png images or csv files
        </p>
        <Upload />
        <div className={styles.grid}>
          <Link href={routes.Images}>
            <a className={styles.card}>
              <h2>Images &rarr;</h2>
              <p>See uploaded images</p>
            </a>
          </Link>
          <Link href={routes.Sheets}>
            <a className={styles.card}>
              <h2>Sheets &rarr;</h2>
              <p>See uploaded sheets</p>
            </a>
          </Link>
        </div>
      </main>
    </div>
  );
};

export default Home;
